### ISSUE TITLE
Automatic formatting is a bad idea

### ISSUE THREAD

**Issue by magical** [hamperbot/hamper#103]
Commit https://github.com/hamperbot/hamper/commit/68fe79c7330a73d8727b49de2100bacbae789485 added some magic behind-the-scenes formatting to the reply method. This is convenient, but also dangerous. Many plugins aren't aware of this formatting step, and perform their own formatting first, putting user-controlled data in the format string.

For example, when the sed command can't find a match for a regex, it [replies](https://github.com/hamperbot/hamper/blob/master/hamper/plugins/commands.py#L91) with an error message including that regex. If that regex happens to contain a valid formatting code, then `reply` will happily format the message again.

It is then trivial to bring down a machine by typing `!s/{user:1000000000}//`, which will be expanded to a 1GB long string.

We either need to update all the plugins to avoid passing user-controlled data to reply, or take the magic formatting out.

**Comment by magical** [comment]
If we really want to keep the magic formatting, another option would be to use a safer method like [string.Template](https://docs.python.org/2/library/string.html#template-strings).

**Comment by justinnoah** [comment]
@magical hamper seems to choke on this instead of causing an expansion problem. If you can replicate this issue, please re-open and explain how. I am not able to trigger this problem.
