### ISSUE TITLE
Birthday announcements

### ISSUE THREAD

**Issue by mathuin** [hamperbot/hamper#122]
It would be nice if hamper could accept self-reported birthdays and send birthday greetings should a user speak in the channel on their birthday.

Greetings should only be sent once per person.

Bonus points if hamper says 'happy belated birthday' to users who speak in the channel for the first time *since* their birthday.  Might want to put a week-long or month-long cap on that, lest it become absurd.

**Comment by mythmon** [comment]
This is a great idea for an external plugin. Lets track that in the meta repo. I filed hamperbot/meta#15 for it.
